services:
  db:
    image: postgres
    restart: always
    shm_size: 256mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: 
      - 5432:5432
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
