services:
  # clickhouse:
  #   image: clickhouse/clickhouse-server:latest
  #   container_name: clickhouse
  #   ports:
  #     - "${DB_PORT}:9000"  # Native interface without tls
  #   volumes:
  #     - clickhouse_data:/var/lib/clickhouse
  #     - clickhouse_config:/etc/clickhouse-server
  #   environment:
  #     CLICKHOUSE_DB: ${DB_NAME:-backlinks}
  #     CLICKHOUSE_USER: ${DB_USER}
  #     CLICKHOUSE_PASSWORD: ${DB_PASSWORD}
  #   restart: unless-stopped

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB : $DB_NAME
      PGDATA: /data/postgres
    volumes:
       - postgres_data:/data/postgres
    ports:
      - "4010:5432"
    restart: unless-stopped

  admin:
    image: adminer
    restart: always
    ports:
      - 4011:8080

  jaeger:
    image: jaegertracing/jaeger:${JAEGER_IMAGE_TAG:-latest}
    volumes:
      - type: bind
        source: monitoring/config-spm.yml
        target: /etc/jaeger/config.yml
    command: ["--config", "/etc/jaeger/config.yml"]
    ports:
      - "16686:16686"
      - "8888:8888"
      - "8889:8889"
      - "4317:4317"
      - "4318:4318"

  prometheus:
    image: prom/prometheus:v3.1.0
    volumes:
    - type: bind
      source: monitoring/prometheus.yml
      target: /etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"


volumes:
  # clickhouse_data:
  # clickhouse_config:
  postgres_data:

