global:
  scrape_interval: 5s
  external_labels:
    monitor: 'bl-monitor'


scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'crawler'
    static_configs:
      - targets: ['localhost:4009']
